<?php

/**
 * @var \Reach\Payment\Block\Adminhtml\Order\View\Info $block
 */

$payment = $block->getPayment();
$dhlbreakdown = $block->getDhlQuoteDetail();

?>

<div class="admin__page-section-item-title" style="margin-top: 20px;">
    <span class="title"><?php echo $block->escapeHtml(__('Reach Information')); ?></span>    
</div>
<div class="admin__page-section-item-content">
    <div class="order-payment-additional order-payment-method-title">
        <table class="data-table admin__table-secondary">
            <tbody>
                    <?php if ($payment->getLastTransId()) : ?>
                <tr>
                    <th><?php echo $block->escapeHtml(__('OrderId')); ?>:</th>
                    <td><?php echo $block->escapeHtml($payment->getLastTransId()); ?></td>
                </tr>
                    <?php endif; ?>
            <?php if ($payment->getAdditionalInformation("contract_id")) : ?>
                <tr>
                    <th><?php echo $block->escapeHtml(__('ContractId')); ?>:</th>
                    <td><?php echo $block->escapeHtml($payment->getAdditionalInformation("contract_id")); ?></td>
                </tr>
            <?php endif; ?>
                <?php if ($payment->getOrder()->getDhlQuoteId()) : ?>
                <tr>
                    <th><?php echo $block->escapeHtml(__('DHL Quote ID')); ?>:</th>
                    <td><?php echo $block->escapeHtml($payment->getOrder()->getDhlQuoteId()); ?></td>
                </tr>
                <?php endif; ?>
            <?php if (isset($dhlbreakdown) && count($dhlbreakdown)) : ?>
                <?php foreach ($dhlbreakdown as $detail) :?>
                    <tr>
                        <th><?php echo $detail['name'] ?>:</th>
                        <td><?php echo $block->formatPrice($detail['value']) ?></td>
                    </tr>
                <?php endforeach;?>
            <?php endif; ?>
            </tbody>
        </table>
    </div>
</div>